title: Rohil Shah
email: rohildshah@ucsb.edu
description: >- # this means to ignore newlines until "baseurl:"
  My personal website.
baseurl: ""
url: https://rohildshah.github.io

# Build settings
theme: minima
plugins:
  - jekyll-feed